services:
  db:
    image: postgres:16
    container_name: freight-portal-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: freight_portal
    ports:
      - "5432:5432"
    volumes:
      - freight-portal-db:/var/lib/postgresql/data

volumes:
  freight-portal-db:
